name: Teams notify
on: [push]

steps:
  name: Send a message to Microsoft Teams
  uses: aliencube/microsoft-teams-actions@v0.8.0
  with:
    webhook_uri: https://outlook.office.com/webhook/8c694645-6335-47bc-8bcc-98438427b8cf@c1503b0c-f258-4400-a061-807980fb5408/IncomingWebhook/48c5229cddc1406483bf7fce3047a185/d33bbb42-64e0-4de8-af6b-038c04c88905
    title: blog.entidia.net deployes
    summary: New Theme Deployment for blog.entidia.net
    text: A new Themeversion has been deployed to blog.entidia.net
    theme_color: #96c300
    sections: '[{ "activityTitle": "hello world" }]'
    actions: '[{ "@type": "OpenUri", "name": "Visit Vlog", "targets": [{ "os": "default", "uri": "https://blog.entidia.net" }] }]'
